# Generated by Django 3.2.21 on 2023-10-11 16:03

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='publish_approved',
        ),
        migrations.AddField(
            model_name='recipe',
            name='approval_status',
            field=models.CharField(choices=[('0', 'Unpublished'), ('1', 'Pending Approval'), ('2', 'Approved'), ('3', 'Rejected')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
