# Generated by Django 3.2.21 on 2023-10-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20231016_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(choices=[('0', '<30 minutes'), ('1', '30 minutes-1 hour'), ('2', '1-2 hours'), ('3', '2-3 hours'), ('4', '3+ hours')], default=1, help_text='Select how long your recipe takes to prepare.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(default='1', help_text='Enter how many people your recipes serves.'),
            preserve_default=False,
        ),
    ]
